### ISSUE TITLE
Fatal issue in Central Agent

### ISSUE THREAD

**Issue by QasimWani** [intelligent-environments-lab/CityLearn#8] opened 2021-11-28 10:45 UTC
https://github.com/intelligent-environments-lab/CityLearn/blob/b451f05cd27bf9d65f45708e3a54daa953056818/citylearn.py#L592

when using central agent, the line referenced above breaks the code because it can't recognize `electrical_storage_soc` state. When modifying the line above such that it takes that state name we have a state size of 102. But when doing `env.reset()`, we have a state size of 93. So, the `electrical_storage_soc` is missing from state, which is expected.
However, in `building_loader`, you have [excluded](https://github.com/intelligent-environments-lab/CityLearn/blob/master/citylearn.py#L177) `electrical_storage_soc` which explains why adding the same conditional fixes the bug to create the agent (bug comes from `reset`) but still the state space is 102 while as `env.reset` is still 93. 
Since you understand the environment better, I must be missing something silly.

Please lmk if you find the issue.

**Comment by nagyzoltan** [comment] 2021-11-28 14:05
Thanks for flagging! I don’t think you’re doing anything silly. We have added that variable ( electrical_storage_soc ) later to the code and it might not be fully tested yet for all use cases (we usually work with the distributed agents one). We’ll take a look.

**Comment by QasimWani** [comment] 2021-12-02 10:33
updates? @kingsleynweye

**Comment by kingsleynweye** [comment] 2021-12-02 10:37
@QasimWani still on it. Should have to fixed by tomorrow.

**Comment by kingsleynweye** [comment] 2021-12-04 19:12
> @QasimWani still on it. Should have to fixed by tomorrow.

@QasimWani I fixed the bug you found locally, but it revealed some other few issues associated with the  `central_agent=True` use case. As @nagyzoltan mentioned, we have not extensively tested the `central_agent=True` use case in the environment. It will take me some more time to fix all issues but I will keep you posted. I will be back with an update later next week. Thanks for your patience on this!

**Comment by HYDesmondLiu** [comment] 2022-07-11 19:23
@kingsleynweye 
Is there any plan to release a tested version for centralized training? Since the centralized version is not ready,
the paper result is not reproducible, am I correct?

**Comment by nagyzoltan** [comment] 2022-07-11 19:33
@HYDesmondLiu which paper are you referring to? We don't typically use the centralized version, only distributed agents. We've been doing some updates and will push a new version soon, in accordance with the citylearn challenge this year https://www.aicrowd.com/challenges/neurips-2022-citylearn-challenge

**Comment by HYDesmondLiu** [comment] 2022-07-11 20:54
@nagyzoltan 
I am sorry I think I misunderstood that parameter setting. 
I am looking forward to the new version update.

**Closed** 2022-08-04 18:36 UTC
